[2025-05-12T19:00:03.879+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T19:00:03.908+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_etl_dag.load_to_redshift_or_s3 scheduled__2025-05-12T18:00:00+00:00 [queued]>
[2025-05-12T19:00:03.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_etl_dag.load_to_redshift_or_s3 scheduled__2025-05-12T18:00:00+00:00 [queued]>
[2025-05-12T19:00:03.912+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-12T19:00:03.917+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_or_s3> on 2025-05-12 18:00:00+00:00
[2025-05-12T19:00:03.919+0000] {standard_task_runner.py:57} INFO - Started process 926 to run task
[2025-05-12T19:00:03.922+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sales_etl_dag', 'load_to_redshift_or_s3', 'scheduled__2025-05-12T18:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/sales_dags.py', '--cfg-path', '/tmp/tmpufx_u2l4']
[2025-05-12T19:00:03.923+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask load_to_redshift_or_s3
[2025-05-12T19:00:03.930+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T19:00:03.945+0000] {task_command.py:415} INFO - Running <TaskInstance: sales_etl_dag.load_to_redshift_or_s3 scheduled__2025-05-12T18:00:00+00:00 [running]> on host 82ee5defb55f
[2025-05-12T19:00:03.952+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T19:00:03.982+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='deepak' AIRFLOW_CTX_DAG_ID='sales_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_redshift_or_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-12T18:00:00+00:00'
[2025-05-12T19:00:03.983+0000] {logging_mixin.py:151} INFO - Loading data to Redshift/S3...
[2025-05-12T19:00:03.983+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-12T19:00:03.987+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=sales_etl_dag, task_id=load_to_redshift_or_s3, execution_date=20250512T180000, start_date=20250512T190003, end_date=20250512T190003
[2025-05-12T19:00:04.021+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-12T19:00:04.029+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
