[2025-05-12T17:54:52.804+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T17:54:52.809+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_etl_dag.load_to_redshift_or_s3 scheduled__2025-05-12T16:00:00+00:00 [queued]>
[2025-05-12T17:54:52.814+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_etl_dag.load_to_redshift_or_s3 scheduled__2025-05-12T16:00:00+00:00 [queued]>
[2025-05-12T17:54:52.815+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-12T17:54:52.822+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_redshift_or_s3> on 2025-05-12 16:00:00+00:00
[2025-05-12T17:54:52.824+0000] {standard_task_runner.py:57} INFO - Started process 263 to run task
[2025-05-12T17:54:52.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sales_etl_dag', 'load_to_redshift_or_s3', 'scheduled__2025-05-12T16:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/sales_dags.py', '--cfg-path', '/tmp/tmpsa7jeat1']
[2025-05-12T17:54:52.827+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask load_to_redshift_or_s3
[2025-05-12T17:54:52.834+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T17:54:52.849+0000] {task_command.py:415} INFO - Running <TaskInstance: sales_etl_dag.load_to_redshift_or_s3 scheduled__2025-05-12T16:00:00+00:00 [running]> on host 82ee5defb55f
[2025-05-12T17:54:52.854+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T17:54:52.880+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='deepak' AIRFLOW_CTX_DAG_ID='sales_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_redshift_or_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-12T16:00:00+00:00'
[2025-05-12T17:54:52.881+0000] {logging_mixin.py:151} INFO - Loading data to Redshift/S3...
[2025-05-12T17:54:52.881+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-12T17:54:52.885+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=sales_etl_dag, task_id=load_to_redshift_or_s3, execution_date=20250512T160000, start_date=20250512T175452, end_date=20250512T175452
[2025-05-12T17:54:52.924+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-12T17:54:52.933+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
