[2025-05-12T21:05:44.584+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-12T21:05:44.613+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: sales_etl_dag.extract_from_kafka scheduled__2025-05-12T20:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-05-12T21:05:44.614+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
